### ISSUE TITLE
How to get JSON array from the intent given by pushy

### ISSUE THREAD

**Issue by abhimuktheeswarar** [pushy-me/pushy-demo-android#1]
Your demo app shows how to get string & int from the intent received in onReceive. But how do I get the json array from the intent. In this case, how to retrive the message array & convert it to string.
Tried this method : `intent.getExtras().getString("message")`, but its throwing error : 
W/Bundle: Key message expected String but value was a [Ljava.lang.Object;.

```
{
  "type": 6,
  "message": [
    {
      "id": "4302",
      "message": "commented",
      "share_count": "0",
      "comment_count": "0",
      "viewCount": "24",
      "content": "",
      "user": {
        "userId": "47050",
        "name": null,
        "topics": ""
      },
      "images": "",
      "comment": "",
      "likes": 4,
      "likeMe": null,
      "ShareCount": 0,
      "saved": 0,
      "going": ""
    }
  ]
}
```

**Comment by pushy** [comment]
Hi @abeemukthees,
Thank you for your report.

Our API will now stringify arrays provided in your push payload, so that you will be able to fetch the stringified JSON array on devices using the following:

```
intent.getExtras().getString("message")
```

You can then inflate the JS array into an `ArrayList` of your custom class using Gson or Jackson.

Please let us know if you need additional clarification or if you still need help with this.

**Comment by abhimuktheeswarar** [comment]
Thanks for the response. I'll try  `intent.getExtras().getString("message") ` it again. Now I'm using jackson to convert the object array
