### ISSUE TITLE
Notification is not received after device is rebooted

### ISSUE THREAD

**Issue by linhnta925** [pushy-me/pushy-demo-android#8]
I'm testing Android SDK version **1.0.54** in my app on a **Sony XZ2** running **Android 10**.
Push notification is working fine when the phone is running.
However, after I restart the phone, it can't receive push notification unless I explicitly open my app.

Is this an expected behavior? Do I have to open the app to receive push notification after the phone is restarted?

**Comment by pushy** [comment]
Hi @tangoclinh1995,
Some devices such as Huawei, Sony, and Xiaomi may not receive notifications after your app is swiped away from the recent apps menu, goes to background, or after a device reboot due to custom power saving features which affect Firebase Cloud Messaging as well.

Most notably, devices from the following manufacturers include custom power-saving restrictions which may hinder background notification delivery for your app:

Xiaomi
Huawei
OnePlus
Samsung
Oppo
Vivo
Asus
Sony
Honor

Unfortunately, since these power saving mechanisms also affect FCM, it is not a Pushy-specific issue, and the only solution is to instruct the user to whitelist your app from the respective manufacturer's power saving mechanism in the Settings. The instructions for doing this vary from one manufacturer to another.

Here are instructions specific to Sony devices:
https://dontkillmyapp.com/sony

We apologize for this inconvenience introduced by some device manufacturers.

**Comment by linhnta925** [comment]
Hi, 

Sorry for false alarm. I found that Pushy can indeed start itself on my Sony SZ2 2 minutes after device is rebooted.

Thanks for making this great service.

**Comment by pushy** [comment]
Hi @tangoclinh1995,

Happy to hear!
You're more than welcome ❤️
